= Completing a Scenario

When a scenario is complete, open the xref:engine:interface:scenarioSetup.adoc[Game Setup] box once again and select btn:[Scenario Won] or btn:[Scenario Lost] to do the following:
* Character standees/minis return to their respective player mats and are reset to full health.
* XP is tallied based on the XP earned from the "dial" plus the bonus XP for the scenario level
* xref:scenario:looting.adoc[Loot] is automatically tallied and added to the character sheet
* Curses and Blesses from all attack modifier decks are returned to their homes.
** Note that any -1(*)s are not removed, as the scripting is not yet set up to handle items. Instead of having anyone with heavy items add their -1s every scenario, the decision was that -1*s not be removed.

Be sure to review the scenario conclusion, adjust the scenario flowchart, gain any party rewards (items, gold, resources, XP, prosperity, inspiration, morale, campaign stickers), check and return your battle goals, or any unlocked mechanics from xref:buildings.adoc[Buildings].

Once the above is complete, you can select btn:[Game Setup] again and click btn:[Delete Map] to remove everything from the table for the scenario you just completed. If you are replaying the scenario, you will have to go through all these steps and re-select this scenario.