= Scenarios

To start building a custom scenario use the https://steamcommunity.com/sharedfiles/filedetails/?id=2494451797[Scenario Builder] mod.
The mod itself contains the information of how to use the builder to generate a scenario.

However, the builder currently only supports a subset of features the scenario definition is able to provide.
E.g. it can't set HP values for overlays, named enemies or loot effects from treasure chests.
To add those features to a scenario, you can edit the generated scenario definition from the Scenario Builder.

NOTE: This section is currently not well documented.
A lot of features are missing...

== Basics

The scenario builder creates a token, that contains the scenario definition within its script.
To adjust the scenario definition, the script has to be changed accordingly.
The script of the tokens looks like this:

[source,lua]
----
include::example$scenario/monster/start.lua[]
----

== General scenario definition structure

.Big example of all the different parts
[%collapsible]
====
[,lua]
----
include::example$scenario/complete_structure.lua[]
----
====

=== Default monster settings

It's possible to define extra attributes, stats, immunities or their used ability deck for all monsters of a given type as part of the scenario definition.
It is possible to distinguish between normal and elite monsters as well.
The general structure looks like this:

[,lua]
----
include::example$scenario/monster/defaults.lua[]
----

The settings from `all` are applied to all monsters that are spawned for this type.
Settings in `normal`/`elite` then are additionally applied to monsters of the given difficulty.

All entries follow the same structure and look like this:

[,lua]
----
include::example$scenario/monster/stats.lua[]
----

The same structure can be applied to an individual monster as well, e.g. to overwrite the stats of a single monster of a given type.
The following example demonstrates this:

[,lua]
----
include::example$scenario/monster/overwrite.lua[]
----

NOTE: While it is possible to define the used ability deck on all levels presented above, it's only useful to use it within the definition of `all`.
It's not possible to have the same monster type with different ability decks, so the first monster that spawns defines the used ability deck for all monsters of that type.
And if the "Preload Enemies" option is used to prepare all monsters in a scenario at its start, the settings for those prepared monsters is only defined by `all` (as those don't have a difficulty setting).
