= Scenarios

To start building a custom scenario use the https://steamcommunity.com/sharedfiles/filedetails/?id=2494451797[Scenario Builder] mod.
The mod itself contains the information of how to use the builder to generate a scenario.

However, the builder currently only supports a subset of features the scenario definition is able to provide.
E.g. it can't set HP values for overlays, named enemies or loot effects from treasure chests.
To add those features to a scenario, you can edit the generated scenario definition from the Scenario Builder.
This, this section contains the documentation about the structure of the scenario definition.
When you want to add or change some features, you need to understand this structure and make those changes accordingly.

In the xref:_concrete_use_cases[] section you can also find examples for specific use-cases to give you an idea on where to start.

NOTE: This section is currently not well documented.
A lot of features are missing...

== Basics

The scenario builder creates a token, that contains the scenario definition within its script.
To adjust the scenario definition, the script has to be changed.
The script on the tokens looks like this:
##
[source,lua]
----
include::example$scenario/start.lua[]
----

To change the scenario definition, change the content between `{}` in the function call to `registerScenario`.
You should also change the scenario ID (the first parameter of the function call, e.g. `Custom Scenario` in the example above).
This ID needs to be unique across all scenarios.

TIP: The ID can also be used to quickly spawn the scenario without using the Game Setup menu.
Enter `>spawn-scenario <scenario-id>` into the chat window (e.g. `>spawn-scenario Custom Scenario` given the example above).
This will delete everything in the scenario play area as well as all monsters and then spawn the new scenario after a short delay.
While this is mainly used for developing purposes, there's nothing stopping you from using it in your gaming sessions as well.

== General scenario definition structure

Collapse the following example to get an overview of the overall scenario definition structure.
The different parts are explained in more details in the following sections.

.Example of all the general scenario definition structure
[%collapsible]
====
[,lua]
----
include::example$scenario/complete.lua[]
----
====

=== Scenario books

The `scenarioBook` property defines which scenario book should be used for the scenario.
It has a `name` property which must match the tag of a registered scenario book.
The `page` property defines which page will be opened, inside the scenario book.
This page will be offset by 1 as it assumes each scenario book has a front cover that is not included in the page numbering.
E.g. if the scenario book is opened with a PDF viewer, the viewer would show page number 4, but the definition would include page number 3.
If the scenario spawns two pages of the scenario book, the property `pageCount` can be set to 2.
More than 2 pages are currently not supported and are probably never required anyway.

[,lua]
----
include::example$scenario/scenario-book/usage.lua[]
----

[#_section_books]
=== Section Books

The `sectionBook` property defines which section book should be used for the scenario.
It has a `name` property which must match the tag of a registered section book.
The `sections` property defines which sections from the book are relevant for this scenario.
The mod will use this information to figure out which pages it needs to spawn from the book.
Each determined page will spawn as a separate book at a fixed position.
Only the buttons for the defined sections will be active, all other sections in the book will simply be black without a button.

[,lua]
----
include::example$scenario/section-book/usage.lua[]
----

=== Default Monster Settings

It's possible to define extra attributes, stats, immunities or their used ability deck for all monsters of a given type as part of the scenario definition.
It is possible to distinguish between normal and elite monsters as well.
The general structure looks like this:

[,lua]
----
include::example$scenario/monster/defaults.lua[]
----

The settings from `all` are applied to all monsters that are spawned for this type.
Settings in `normal`/`elite` then are additionally applied to monsters of the given difficulty.

All entries follow the same structure and look like this:

[,lua]
----
include::example$scenario/monster/stats.lua[]
----

The same structure can be applied to an individual monster as well, e.g. to overwrite the stats of a single monster of a given type.
The following example demonstrates this:

[,lua]
----
include::example$scenario/monster/overwrite.lua[]
----

NOTE: While it is possible to define the used ability deck on all levels presented above, it's only useful to use it within the definition of `all`.
It's not possible to have the same monster type with different ability decks, so the first monster that spawns defines the used ability deck for all monsters of that type.
And if the "Preload Enemies" option is used to prepare all monsters in a scenario at its start, the settings for those prepared monsters is only defined by `all` (as those don't have a difficulty setting).

=== Figures

Similar to the Monsters option, you can spawn scenario specific figures which perform the same action each round. This is commonly used for named allies or unique basic enemies. These figures require a standee model which can be based on any existing summon or enemy, or you can register a custom figure (objects with the "Figure" tag included within a "Gloomhaven Custom Content" bag).

====
.Figures
[source,lua]
----
figures = {
  ["Mechanical Turret"] = {
    --name of the Summon, Enemy, or registered Figure object to use as a standee
    basedOn = "Ancient Artillery",
    --possible base values are "Normal" (White), "Elite" (Yellow), "Ally" (Blue), "Boss" (Red) and "Named" (Purple) 
    base = "Normal",
    stats = {
      health = 10,
      attributes = {
        add = { Shield = 1 },
      },
      immunities = {
        add = { "Poison" },
      },
    },
    ability = {
      initiative = 50,
      ability = "{e.Attack}3 {e.Range}4",
    },
  },
},
----
====

When placing a figure within a room, you can also exclude it from spawning with different player counts.

====
.Placed Figures
[source,lua]
----
figures = {
  [1] = {
    name = "Mechanical Turret",
    position = { x = '15.15', y = '1.76', z = '-8.75', },
    rotation = { x = '0.00', y = '180.00', z = '0.00', },
    characterCount = {
      [2] = R.Remove,
      [3] = R.Remove,
    },
  },
},
----
====

=== Overlays

You can define the conditions and name for overlays, commonly used for traps:

====
.Overlays
[source,lua]
----
overlays = {
  --This is the original overlay tile's name.
  ["Bear Trap"] = {
    --These are the trap conditions applied when triggered.
    conditions = { "Damage" },
    --This is the new name given to all overlays of this type when spawned durign scenario setup.
    name = "Damage Trap",
  },
},
----
====

=== Objectives

You can add a Scenario Aid token to an object's UI, or even include a health bar:

====
.Objectives
[source,lua]
----
overlayTiles = {
  {
    bag = R.ElementType.Obstacle,
    type = {
      {
        name = "Rock Column",
        tiles = {
          {
            position = { x = -1.31, y = 1.87, z = 9.85, },
            rotation = { x = 0, y = 0, z = 0, },
            name = "Summoning Stone",
            tokens = { "a" },
            hp = {"+", "C", 1},
          },
        },
      },
    },
  },
},
----
====

=== Actions

For a complete list of actions available, see Common > Actions: https://gloomhaven-tts-enhanced.github.io/public-scripts/custom/1.3/common/action.html.

[#_frequently_used_actions]
=== Frequently used actions

You can add a Treasure action to an object (typically a treasure chest) to spawn the card defined as treasure:
====
.Treasure
[source,lua]
----
action = {
  name = "50",
  treasure = "Treasure 50",
},
----
====

You can set the chest as a scenario goal as well:
====
.Treasure (G)
[source,lua]
----
action = {
  treasure = "G",
},
----
====

You can add an action to an objective to act as a door. Triggering this can be used to reveal hidden rooms or spawn additional enemies:
====
.Door/Rooms
[source,lua]
----
action = {
  rooms = { 6, 2 }
}
----
====

=== Tags

You may need to add `tags` to an overlay or standee when it's spawned so that you can build actions to interact with it. A common use is to remove the object as part of an action.
====
.Adding tags to an object
[source,lua]
----
overlayTiles = {
  {
    bag = R.ElementType.Obstacle,
    type = {
      {
        name = "Nest",
        tiles = {
          {
            position = { x = 3.94, y = 1.86, z = 6.82, },
            rotation = { x = 0, y = 0, z = 0, },
            tags = {"Scenario X Nest 1"},
          },
        },
      },
    },
  },
},
----
====

=== Randomly placed objects

Some scenarios require to place some objects randomly during setup, e.g. placing objective tokens face down or spawn the content of a random dungeon card.

[#_extra_content]
=== Extra content

As a fallback mechanism extra scenario components can be defined.
This is meant to easily supply objects that are currently not supported through scripting (e.g. monsters that use different attack modifier decks).
Those first have to be registered inside a xref:contentbox.adoc[Custom Content Box].
Then inside the scenario definition, they can be references by their name and be placed at a specific position.

It's possible to define the extra components on the top-level of the scenario and also on each room.
When defined on the top-level the components will spawn, once the scenario is loaded.
Components defined on a room are loaded once the rooms is opened.

Both entries are lists, so they can define multiple components.

[,lua]
----
include::example$scenario/extra/usage.lua[]
----

[#_concrete_use_cases]
== Concrete use-cases

The examples in this section create a `local` variable named `scenario`.
This contains the relevant part of the scenario definition for the example and is the part that would be passed to `registerScenario`.

=== Custom monster ability decks

Changes the ability deck monsters will use.

[,lua]
----
include::example$scenario/use-case/ability-deck.lua[]
----

=== Extra content

Loads additional components as a fall-back that are currently not supported with scripting (also known as "asshole bags").

[,lua]
----
include::example$scenario/use-case/extra-content.lua[]
----
