= Scenarios

To start building a custom scenario use the https://steamcommunity.com/sharedfiles/filedetails/?id=2494451797[Scenario Builder] mod.
The mod itself contains the information of how to use the builder to generate a scenario.

However, the builder currently only supports a subset of features the scenario definition is able to provide.
E.g. it can't set HP values for overlays, named enemies or treasure chests.
To add those features to a scenario, you can edit the generated scenario definition from the Scenario Builder.

== Components


=== Scenario Token
[cols="1,2"]
|===
| Name | Unique identifier across all scenarios.
| Tags | Scenario
|===

This is the token that is generated by the Scenario Builder.
The Builder doesn't set a name for the token though, so that has to be done manually afterwards.
The scenario needs to be inside a <<Custom_Content_Box>> to be registered correctly.

== Data

The Scenario Builder generates a Scenario Token with a script, that looks like this:

[source,lua]
----
local scenario = {
    -- scenario definition
}
function onLoad()
    -- code to create a button
end

function spawnScenario()
    -- function to spawn the scenario
end
----

In order to fully register the scenario, this script has to be slightly adjusted.
Replace the script from the token to the following one, where you copy the content of `scenario` from the generated script and paste it here.

.api/GloomApi.ttslua
[source,lua]
----
local ScenarioApi = require("api.ScenarioApi")

local scenario = {
    -- scenario definition generated from the Builder
}

function onLoad()
    ScenarioApi.registerScenario("Custom001", scenario)
end
----

=== registerScenario

Registers a scenario for the mod (see <<Example_Scenario>> for examples).

Parameters::

[cols="1,1,1,2"]
|===
| Name | Required | Type | Description

| name          | required | String | The name of the class.
| scenarioInfo  | required | <<ScenarioInfo>> | The information about the scenario.
|===
