packages:
  - "packages/*"
  - docs
catalog:
  "@antora/cli": ~3.0.1
  "@antora/lunr-extension": 1.0.0-alpha.8
  "@antora/site-generator": ~3.0.1
  date-fns: ~2.29.3
  "@gloomhaven-enhanced/data": ~0.1.0
  tsx: ~4.19.0
  typescript: 5.8.2
  yaml: ~2.7.0
  yargs: ~17.6.2
  "@types/yargs": ~17.0.33
