= Command Line

The mod integrates a very basic command line feature, to simplify some steps during development.
It can be used by typing a command into the chat window.
Commands always start with an `>`.
The text after the space is the argument that is passed to the command (if the command uses it).

====
Example command named `log-level`.
The argument passed to the command will be `debug`.

----
>log-level debug
----
====

Every print is also sent to the Atom plugin and the console in Atom (can be opened with kbd:[Ctrl+Shift+I]).
From there it can be copied.

== Setting the Logging Level

Sets the level of all loggers.
All log messages with a higher or equal level will be printed to the game chat.
The default level is `INFO`.

Available levels are (in descending order): `ERROR`, `WARNING`, `INFO`, `DEBUG` and `VERBOSE`.
The values are case-insensitive.

====
----
>log-level debug
----
====

== Get Position

Prints the position and rotation of the object that is currently hovered by the player entering the command.
This might be useful to determine where a certain object is placed, e.g. if that is manually entered into a scenario definition.

====
----
>show-pos
----

.Output
----
position = { -12.25, 1.65, -13.3 },
rotation = { 0, 0, 0 },
----
====

== Spawn scenario

Spawns a scenario with the given ID.
Also deletes all objects in the scenario area.

====
----
>spawn-scenario 10
----
====
