= Setup

== Installation

The following tools need to be present on your system to effectively work with the mod and its tools.

https://git-scm.com/[git]:: To synchronize changes on the local file system with the one on GitHub.
By default, this comes with a command line tool and a bare-bones UI.
It's recommended to also install other tools that offer better UIs to effectively work with git, like https://github.com/apps/desktop[GitHub Desktop] or the integration in editors like https://code.visualstudio.com/[Visual Studio Code]

https://nodejs.org/[node.js]:: An engine to execute JavaScript/TypeScript code.
Most tools surrounding the mod are written with TypeScript so this needs to be installed to execute them.

https://pnpm.io/[pnpm]:: A package manager for external libraries used by the tools.
Also mainly used to actually start the different tools from a command line.

https://code.visualstudio.com/[Visual Studio Code]:: A multipurpose text-editor/development tool.
Makes it easier to read and write the mod's code and work with the tools.
Also has extensions that make it integrate into TTS directly, like https://marketplace.visualstudio.com/items?itemName=sebaestschjin.tts-editor[this one].

Inside the https://kb.tabletopsimulator.com/getting-started/technical-info/#save-game-data-location[TTS save game directory] create the following files:

* Enginehaven_Dev.json
* Frosthaven_Dev.json

The content doesn't matter, just their existence is important.

== Basic workflow

After installing everything, clone the repository with git somewhere on your local filesystem.
Then run the command `pnpm install` via a command line.
This will install the external dependencies required for the tools in the repository.
Finally, run the command `pnpm compile` via a command line.
This will build the tools on your local file system so they are ready to use.

Whenever you perform a `git pull` to get the latest changes from GitHub, a `pnpm install` will typically be automatically executed if it is required.
It's also recommended to execute the `pnpm compile` command again then to build any updates to the tools.
This is not done automatically.

To create the latest save games of the mod based on the current state of the repository, run the command `pnpm embed:fh`.
This will fill the previously created files `Enginehaven_Dev.json` and `Frosthaven_Dev.json` with actual TTS save files.
Load the save `Enginehaven_Dev` inside TTS.
Then additively load `Frosthaven_Dev`.
Save the game and load it again, you now have the current copy of Frosthaven Enhanced.
