= Scenario Basics

* Click xref:campaign:start.adoc[here] to review setting up a scenario.
* Additional Notes
** To change scenario aid tokens or objective tokens: right-click, select "Change Text", and update to appropriate text.
** In addition to accessing a player's attack modifier deck from the xref:engine:interface/interfaces.adoc#player_interface[Player Interface], a player's attack modifier may be drawn by clicking btn:[Draw] near their attack modifier deck on their player mat.
** Similarly, character blesses and curses may be added from the buttons just above the btn:[Draw] and btn:[Shuffle].
** Right clicking a +/- button for counters on the character sheet will add/remove a value by 5. Middle click will add/remove by 10.
** Before a round can start, every character must place cards into their 1 and 2 slots on their player mat.
*** Press 1 when hovering on a card to put it in slot 1, and Press 2 to do so for slot 2.
** If they instead wish to long rest, they must click btn:[Long Rest] in their xref:engine:interface/interfaces.adoc#player_interface[Player Interface].

