= Scenarios

== Base information

[source,js]
----
include::example$scenario-2.ts[tags=base]
----

[cols="m,3a"]
|===
| campaign |  The name of the campaign this scenario belongs to.
This is important for the mod to know as it uses this name to check certain things, like the rules for the campaign, which scenario/section book to use by default, etc.

| index |  The identifier by which this scenario will be identified by the mod.
Typically, the number of the scenario (but still as a string).

| name |  The name of the scenario.

| location |  Where the scenario takes places.
Can have an optional `name` for a named location this scenario takes place at.
The `coordinate` describes the location on the world map for this scenario.

| complexity |  The complexity rating for the scenario.

| scenarioBook |  Contains information about the scenario book for this scenario.
Mainly, which `page` of the book should be opened when the scenario is loaded.

| sectionBook |  Contains information about the section book for this scenario.
Lists all the `sections` that are relevant for this scenario.

NOTE: Currently, all sections have to be listed.
However, in a future version this will probably be reworked as the information about sections is also present in other parts of the scenario definition (e.g. on doors).
|===

== Available loot

The loot table for a scenario is defined by the `loot` attribute.
It defines how many cards of each type should be added to the loot deck.
Each entry for a resource is lower case and follows the name of the resource/herb.
If a random item can also be looted in the scenario, the attribute `randomItem` can be added with the value `true`.

[source,js]
----
include::example$scenario-2.ts[tags=loot,indent=]
----

== Scenario goal

The goal of the scenario can be defined using the `goal` attribute.
Depending on the type of goal, different attributes are available.

If the goal is to defeat all enemies in the scenario, the `type` attribute needs to be set to `defeat-all`.
The `section` attribute defines the section that should be read once the goal is achieved.

[source,js]
----
include::example$goal/defeat-all.ts[]
----

If the goal is to defeat a specific enemy in the scenario, the `type` attribute needs to be set to `defeat`.
The `name` attribute defines the name of the enemy that must be defeated.

[source,js]
----
example pending
----

If the goal is to escape the scenario, the `type` attribute needs to be set to `escape`.
The `section` attribute defines the section that should be read once the goal is achieved.

[source,js]
----
include::example$goal/escape.ts[]
----

If the goal is to destroy one or more objectives in the scenario, the `type` attribute needs to be set to `destroy`.
The `marker` attribute defines (pending).

[source,js]
----
example pending
----

If no specific type matches the goal, use the `other` `type`.

[source,js]
----
include::example$goal/other.ts[]
----

NOTE: This currently has no effect at all and also not complete.
It's already included for possible later features, like showing and tracking the current scenario goal or to add the correct sections to the section book.

== Scenario effects

Scenario effects can be defined using the `scenarioEffect` attribute.
Depending on the type of effect, different attributes are available.

If the effect is to add -1 modifiers to the characters' attack modifier deck, the `type` attribute needs to be set to `attack-modifier`.
The `card` attribute defines the type of modifier added, which would only be `-1`,`curse`, or `bless` (note: curse and bless are not yet supported).
The `amount` attribute defines how many of that card type should be added.

[source,js]
----
include::example$goal/escape.ts[]
----

If the effect is for the characters to suffer damage, the `type` attribute needs to be set to `damage`.
The `amount` attribute defines how damage should be suffered.

[source,js]
----
include::example$goal/escape.ts[]
----

If the effect is to add one or more conditions to the characters, the `type` attribute needs to be set to `condition`.
The `conditions` string defines a list of each condition that should be added.

[source,js]
----
include::example$goal/escape.ts[]
----

NOTE: This currently has no effect at all and also not complete.
It's already included for possible later features, like automatically applying scenario effects unless the character has a perk to ignore them.

[#monsters]
== Monsters

Each monster that shows up in the scenario needs to be defined through the `monsters` attribute.
This is a table from their name extra information for the monster.
This information can be empty if there's nothing special about the monster.

The name doesn't have to match the actual name of the monster and can possibly be anything.
When monsters are placed in <<rooms>> the names used there must match one of the monster names defined in this section.
Whenever a named version of a monster exists, it must have the `monster` attribute to define the original type of that monster, and the `name` attribute to define the name that should be used on the figure.

[source,js]
----
include::example$scenario-2.ts[tags=monster,indent=]
----

More details about how to define monsters can be found xref:monsters.adoc[here].

[#overlays]
== Overlays

Each overlays that shows up in the scenario needs to be defined through the `overlays` attribute.
This is a table from their name to their extra information.
Each overlay at least needs to define their `type` which determines the outline color that will be used for the overlay.

The name doesn't have to match the actual name of the overlay object and can possibly be anything.
When overlays are placed in <<rooms>> the names used there must match one of the overlay names defined in this section.

[source,js]
----
include::example$scenario-2.ts[tags=overlays,indent=]
----

More details about how to define overlays can be found xref:overlays.adoc[here].

[#doors]
== Doors

Doors need to be defined with the `doors` attribute.
This is a list of door objects that will be placed once their corresponding rooms have been opened.

[source,js]
----
include::example$scenario-2.ts[tags=doors,indent=]
----

[cols="m,3"]
|===
| name |  The name of the overlay object to use for the door.
It can be any object and isn't limited to an actual door.
This doesn't use any information from the <<overlays>> section.
| rooms |  The list of rooms that this door opens.
The rooms are listed with their `index` attribute.
| section |  The name of the section that should be read when this door is opened.
| position |  The position of the object on the xref:grid.adoc[].
|===

[#rooms]
== Rooms

A scenario consists of multiple rooms.
Each room can spawn new maps, monster, overlays, loot etc.
The `rooms` attribute is a list of those rooms and each room has the same attributes.

Each room needs to have an `index` attribute which identifies the room.
This can be any name.
<<doors>> open rooms by their `index`.

[source,js]
----
include::example$scenario-2.ts[tags=rooms-base,indent=]
----

Only the very first room in the list will be loaded first when the scenario is loaded.

If the room contains map tiles, those can be defined with the `map` attribute.
This is a list of map tiles and their position.

[source,js]
----
include::example$scenario-2.ts[tags=rooms-map,indent=]
----

Each map tile has the following properties:

[cols="m,3"]
|===
| name |  The name of the map tile object.
| position |  The position of the map tile on the xref:grid.adoc[].
| rotation |  The rotation of the map tile.
|===

NOTE: A room without map tiles isn't really a "room" but can be useful for scripting the scenario.
E.g. scenario 4 has a "dummy" room as its starting room which only contains two overlays with buttons.
Those buttons are used to represent the choice of introduction to read for this scenario.

If there are start tiles inside the rooms, those can be defined with the `startArea` attribute.
This is a list of coordinates on the xref:grid.adoc[].

[source,js]
----
include::example$scenario-2.ts[tags=rooms-start,indent=]
----

If there are monsters for this room, those can be defined with the `monsters` attribute.
This is a list of monsters which will be spawned when this room is opened.

[source,js]
----
include::example$scenario-2.ts[tags=rooms-monsters,indent=]
----
Each monster has the following properties:

[cols="m,3"]
|===
| name | The name of the monster.
This must match one of the defined monsters in the <<monsters>> section.
| position | The position of the monster on the xref:grid.adoc[].
| playerCount | Defines for which players the monster shows up and which difficulty it has.
If a mapping for a player count is missing, the monster won't show up.
Otherwise, the mapping needs to define either `"normal"` or `"elite"` for the difficulty of the monster.
|===

If there are overlays for this room, those can be defined with the `overlays` attribute.
This is a list of overlays which will be spawned when this room is opened.

NOTE: Loot tokens are _not_ overlays and are defined in their own section.

[source,js]
----
include::example$scenario-2.ts[tags=rooms-overlays,indent=]
----

Each overlay has the following properties:

[cols="m,3"]
|===
| name | The name of the overlay.
This must match one of the defined overlays in the <<overlays>> section.
| position | The position of the overlay on the xref:grid.adoc[].
| rotation | The rotation of the overlay.
This is optional and will default to the rotation of the defined overlay or 0 if there's also nothing defined.
|===

Loot tokens defined with the `loot` attribute by simply defining their position on the grid.

[source,js]
----
include::example$scenario-2.ts[tags=rooms-loot,indent=]
----

